# Generated by Django 4.2 on 2023-04-19 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import submission.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ca33996c-ab88-4fe9-8ce8-5e428cd255ed'), primary_key=True, serialize=False)),
                ('submission_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('File', 'FILE'), ('LINK', 'LINK')], default='LINK', max_length=10)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=submission.models.username_path)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=submission.models.username_path)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
