# Generated by Django 4.2 on 2023-04-19 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63517c52-2943-4d13-934d-9dc7dfb7de5a'), primary_key=True, serialize=False),
        ),
    ]
