# Generated by Django 4.2 on 2023-04-19 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cebd309d-b46d-4a0a-a7d8-bb122b91fabd'), primary_key=True, serialize=False),
        ),
    ]
