# Generated by Django 4.2 on 2023-04-19 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76dc8332-b400-4174-9a49-bfd6348bf257'), primary_key=True, serialize=False),
        ),
    ]
