# Generated by Django 4.2 on 2023-04-19 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56174acf-2930-4d77-8577-4169629db224'), primary_key=True, serialize=False),
        ),
    ]
