# Generated by Django 4.2 on 2023-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_hackathon_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='hackathon_image',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='submission_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('FILE', 'File'), ('LINK', 'Link')], default='LINK', max_length=6),
        ),
    ]
