# Generated by Django 4.2 on 2023-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_hackathon_background_image_hackathon_hackathon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
